### ISSUE TITLE
[Dúvida] Exemplo

### ISSUE THREAD

**Issue by alegsantos** [ACBrNet/ACBr.Net.DFe.Core#2]
Olá amigo!

Parabéns pela iniciativa. Uso atualmente o ACBR no Delphi. Tem algum exemplo de como usar este componente com C#? Grande abraço.

**Comment by rftd** [comment]
qual exemplo se gostaria, esta lib aqui é usada pelos outros componentes, não foi feita para ser usada diretamente pelo usuário.

**Comment by alegsantos** [comment]
Gerar/Assinar e Transmitir a NFe

**Comment by rftd** [comment]
Não temos este componente disponível ainda, apenas, CTe, SAT e NFSe.

**Comment by alegsantos** [comment]
Valeu amigo.
