### ISSUE TITLE
Serialização de classes distintas com mesmo nome de elemento

### ISSUE THREAD

**Issue by marcosgerene** [ACBrNet/ACBr.Net.DFe.Core#5]
![image](https://user-images.githubusercontent.com/15945003/116074967-c82af480-a668-11eb-93ce-eb7fff8eadad.png)

No GNRe existe duas versões (1.00 e 2.00) e ambas são COMPLETAMENTE diferentes uma da outra, mas no xml usam a mesma definiçao ```TLote_GNRE```  de ```DFeElement``` e a única separação entre eles é o atributo "versão".

Bem, a minha ideia é realmente fazer classes diferentes para cada tipo de versão, talvez até funcione para serealizar, mas na desserialização acredito que não terei sucesso.

![image](https://user-images.githubusercontent.com/15945003/116075419-4e473b00-a669-11eb-8ea5-da7225c4495f.png)

Qual a melhor forma de fazer isso?

https://github.com/marcosgerene/Gerene.Gnre/issues/2

**Comment by rftd** [comment]
Neste caso em vez de fazer 2 classes faça 1 apenas com todos as propriedades e use os métodos ShouldSerialize de acordo com a versão usada no att versao

**Comment by marcosgerene** [comment]
@rftd  boa, vou estudar a ideia, obrigado
